// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-P-JmX8IN79Bkg_7qtwnT7yKMqmbw_-8',
    appId: '1:544522747476:web:c1bc60b589da2cbb4737c1',
    messagingSenderId: '544522747476',
    projectId: 'midd-ffa10',
    authDomain: 'midd-ffa10.firebaseapp.com',
    databaseURL: 'https://midd-ffa10-default-rtdb.firebaseio.com',
    storageBucket: 'midd-ffa10.appspot.com',
    measurementId: 'G-E66FBSKTVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOjOCE6es6DfN45Wv1Pm2aKJQ9z2oG3ac',
    appId: '1:544522747476:android:86d546f96e53b5264737c1',
    messagingSenderId: '544522747476',
    projectId: 'midd-ffa10',
    databaseURL: 'https://midd-ffa10-default-rtdb.firebaseio.com',
    storageBucket: 'midd-ffa10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlrx6xIkljlywm2r7YDvrHitdibKbbCuQ',
    appId: '1:544522747476:ios:c553cd7be31e627c4737c1',
    messagingSenderId: '544522747476',
    projectId: 'midd-ffa10',
    databaseURL: 'https://midd-ffa10-default-rtdb.firebaseio.com',
    storageBucket: 'midd-ffa10.appspot.com',
    iosBundleId: 'com.example.midd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlrx6xIkljlywm2r7YDvrHitdibKbbCuQ',
    appId: '1:544522747476:ios:87b87dd830f5a6c74737c1',
    messagingSenderId: '544522747476',
    projectId: 'midd-ffa10',
    databaseURL: 'https://midd-ffa10-default-rtdb.firebaseio.com',
    storageBucket: 'midd-ffa10.appspot.com',
    iosBundleId: 'com.example.midd.RunnerTests',
  );
}
